default: &default
  google_client_id: <%= ENV["GOOGLE_CLIENT_ID"] %>
  google_client_secret: <%= ENV["GOOGLE_CLIENT_SECRET"] %>
  amazon_client_id: <%= ENV["AMAZON_CLIENT_ID"] %>
  amazon_client_secret: <%= ENV["AMAZON_CLIENT_SECRET"] %>
  windowslive_client_id: <%= ENV["WINDOWSLIVE_CLIENT_ID"] %>
  windowslive_client_secret: <%= ENV["WINDOWSLIVE_CLIENT_SECRET"] %>
  approval_sender: user@example.org
  approval_receiver: list@example.org

development:
  <<: *default
  secret_key_base: 95980b31ea342c0d5bfe99c61df67c2fe2f1c54b38a37707e48513c7b4ec147e88dc1236a1a516643d2e99de433bedaf9313b72a6240fd67ab45e62adb1b23c9

test:
  <<: *default
  secret_key_base: dd162ad362bf87c583a0b72c695bd4db8a3cd71032931157f09b02f07b6bc96f4b2370269ec68ff516f292873b12f961de3de963b6c282091fcce4b703350f61

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  <<: *default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  approval_sender: lr-approval@gmail.com
  approval_receiver: lr-approval@googlegroups.com
