nodeTemplate ={'community_description': {'active': True,
                           'community_admin_identity': 'community.admin@learningregistry.org',
                           'community_description': 'Learning Registry Open, Public Community',
                           'community_id': 'Learning Registry Open, Public Community',
                           'community_name': 'Learning Registry Open, Public Community',
                           'doc_scope': 'community',
                           'doc_type': 'community_description',
                           'doc_version': '0.20.0',
                           'social_community': True},
 'network_description': {'active': True,
                         'community_id': 'Learning Registry Open, Public Community',
                         'doc_scope': 'network',
                         'doc_type': 'network_description',
                         'doc_version': '0.20.0',
                         'network_admin_identity': 'network.admin@learningregistry.org',
                         'network_description': 'Learning Registry Open, Public Network',
                         'network_id': 'Learning Registry Open, Public Network',
                         'network_name': 'Learning Registry Open, Public Network'},
 'network_policy_description': {'TTL': 400,
                                'active': True,
                                'doc_scope': 'network',
                                'doc_type': 'policy_description',
                                'doc_version': '0.10.0',
                                'network_id': 'Learning Registry Open, Public Network',
                                'policy_id': 'Learning Registry Open, Public Network Policy',
                                'policy_version': '0.10.0'},
 'node_description': {'active': True,
                      'community_id': 'Learning Registry Open, Public Community',
                      'doc_scope': 'node',
                      'doc_type': 'node_description',
                      'doc_version': '0.23.0',
                      'gateway_node': False,
                      'network_id': 'Learning Registry Open, Public Network',
                      'node_admin_identity': 'http://localhost:5000.node.admin@learningregistry.org',
                      'node_description': 'Node@http://localhost:5000',
                      'node_id': '934efe7790264ce8ab278c3e9b3d66e6',
                      'node_name': 'Node@http://localhost:5000',
                      'node_policy': {'deleted_data_policy': 'no'},
                      'open_connect_dest': True,
                      'open_connect_source': True},
 'node_filter_description': {},
 'node_services': [{'active': True,
                    'doc_scope': 'node',
                    'doc_type': 'service_description',
                    'doc_version': '0.20.0',
                    'service_auth': {'service_authz': ['none'],
                                     'service_https': False,
                                     'service_key': False},
                    'service_endpoint': 'http://localhost:5000/distribute',
                    'service_id': '104ae89ff1754a6190bd3ee06d887cfc',
                    'service_name': 'Resource Data Distribution',
                    'service_type': 'access',
                    'service_version': '0.10.0'},
                   {'active': True,
                    'doc_scope': 'node',
                    'doc_type': 'service_description',
                    'doc_version': '0.20.0',
                    'service_auth': {'service_authz': ['none'],
                                     'service_https': False,
                                     'service_key': False},
                    'service_data': {'flow_control': False,
                                     'granularity': 'YYYY-MM-DDThh:mm:ssZ',
                                     'metadataformats': [{'metadataFormat': 'LR Resource Data Description Data Model',
                                                          'metadataPrefix': 'LR_JSON_0.10.0'}],
                                     'setSpec': None},
                    'service_endpoint': 'http://localhost:5000/harvest',
                    'service_id': 'c7d00faecab54d43910c09ffe9a2d774',
                    'service_name': 'Basic Harvest',
                    'service_type': 'access',
                    'service_version': '0.10.0'},
                   {'active': True,
                    'doc_scope': 'node',
                    'doc_type': 'service_description',
                    'doc_version': '0.20.0',
                    'service_auth': {'service_authz': ['none'],
                                     'service_https': False,
                                     'service_key': False},
                    'service_data': {'flow_control': False,
                                     'spec_kv_only': False},
                    'service_endpoint': 'http://localhost:5000/obtain',
                    'service_id': 'a4f9bc56bd2c4a61bd010980182a1ffb',
                    'service_name': 'Basic Obtain',
                    'service_type': 'access',
                    'service_version': '0.21'},
                   {'active': True,
                    'doc_scope': 'node',
                    'doc_type': 'service_description',
                    'doc_version': '0.20.0',
                    'service_auth': {'service_authz': ['none'],
                                     'service_https': False,
                                     'service_key': False},
                    'service_endpoint': 'http://localhost:5000/description',
                    'service_id': '280eaf8ee8df447881ef8271edd7914c',
                    'service_name': 'Network Node Description',
                    'service_type': 'access',
                    'service_version': '0.10.0'},
                   {'active': True,
                    'doc_scope': 'node',
                    'doc_type': 'service_description',
                    'doc_version': '0.20.0',
                    'service_auth': {'service_authz': ['none'],
                                     'service_https': False,
                                     'service_key': False},
                    'service_data': {'flow_control': False,
                                     'granularity': 'YYYY-MM-DDThh:mm:ssZ',
                                     'schemalocation': 'http://www.learningregistry.org/documents/downloads/OAI-PMH-LR.xsd',
                                     'version': 'OAI-PMH 2.0'},
                    'service_endpoint': 'http://localhost:5000/OAI-PMH',
                    'service_id': '8edca190062a4b278648b1356ecb4bdd',
                    'service_name': 'OAI-PMH Harvest',
                    'service_type': 'access',
                    'service_version': '0.10.0'},
                   {'active': True,
                    'doc_scope': 'node',
                    'doc_type': 'service_description',
                    'doc_version': '0.20.0',
                    'service_auth': {'service_authz': None,
                                     'service_https': False,
                                     'service_key': False},
                    'service_data': {},
                    'service_description': 'access SWORD APP Publish V1.3 service',
                    'service_endpoint': 'http://localhost:5000/SWORD APP Publish V1.3',
                    'service_id': 'a8cd6e539d37461586c9e464120b61cf',
                    'service_name': 'SWORD APP Publish V1.3',
                    'service_type': 'access',
                    'service_version': '0.1'},
                   {'active': True,
                    'doc_scope': 'node',
                    'doc_type': 'service_description',
                    'doc_version': '0.20.0',
                    'service_auth': {'service_authz': ['none'],
                                     'service_https': False,
                                     'service_key': False},
                    'service_data': {'flow_control': False},
                    'service_endpoint': 'http://localhost:5000/slice',
                    'service_id': '58f5a8608e484bf1b01336c593788b4d',
                    'service_name': 'Slice',
                    'service_type': 'access',
                    'service_version': '0.10.0'},
                   {'active': True,
                    'doc_scope': 'node',
                    'doc_type': 'service_description',
                    'doc_version': '0.20.0',
                    'service_auth': {'service_authz': None,
                                     'service_https': False,
                                     'service_key': False},
                    'service_data': {},
                    'service_description': 'administrative Network Node Services service',
                    'service_endpoint': 'http://localhost:5000/Network Node Services',
                    'service_id': '39f1a356d51948cfb1b560cb86bf0bc1',
                    'service_name': 'Network Node Services',
                    'service_type': 'administrative',
                    'service_version': '0.1'},
                   {'active': True,
                    'doc_scope': 'node',
                    'doc_type': 'service_description',
                    'doc_version': '0.20.0',
                    'service_auth': {'service_authz': None,
                                     'service_https': False,
                                     'service_key': False},
                    'service_data': {},
                    'service_description': 'administrative Network Node Status service',
                    'service_endpoint': 'http://localhost:5000/Network Node Status',
                    'service_id': '81a82247f1c1492c8591e3fb79f2b200',
                    'service_name': 'Network Node Status',
                    'service_type': 'administrative',
                    'service_version': '0.1'},
                   {'active': True,
                    'doc_scope': 'node',
                    'doc_type': 'service_description',
                    'doc_version': '0.20.0',
                    'service_auth': {'service_authz': None,
                                     'service_https': False,
                                     'service_key': False},
                    'service_data': {},
                    'service_description': 'administrative Resource Distribution Network Policy service',
                    'service_endpoint': 'http://localhost:5000/Resource Distribution Network Policy',
                    'service_id': 'f3ec52a1742b474a86b4e8c4c24ff871',
                    'service_name': 'Resource Distribution Network Policy',
                    'service_type': 'administrative',
                    'service_version': '0.1'},
                   {'active': True,
                    'doc_scope': 'node',
                    'doc_type': 'service_description',
                    'doc_version': '0.20.0',
                    'service_auth': {'service_authz': ['none'],
                                     'service_https': False,
                                     'service_key': False},
                    'service_data': {'doc_limit': 1, 'msg_size_limit': 0},
                    'service_endpoint': 'http://localhost:5000/publish',
                    'service_id': 'e07d1ffd8d584e4c8c370a92ce3b1929',
                    'service_name': 'Basic Publish',
                    'service_type': 'publish',
                    'service_version': '0.23.0'}]}
