#! /bin/bash
# /etc/init.d/learningregistry
#

LR_HOME=/home/learningregistry/gitrepos/LearningRegistry/LR
LR_USER=learningregistry
LR_GRP=learningregistry
LR_VIRTUALENV=/home/learningregistry/virtualenv/lr
LR_PID_DIR=/var/run/learningregistry
LR_LOG_DIR=/var/log/learningregistry

LR_PID=$LR_PID_DIR/uwsgi.pid
LR_LOG=$LR_LOG_DIR/uwsgi.log

LR_PROC_COUNT = 4

# Some things that run always
if [ ! -e $LR_PID_DIR ]
then
    mkdir -p $LR_PID_DIR
    chown $LR_USER:$LR_GRP $LR_PID_DIR
fi

if [ ! -e $LR_LOG_DIR ]
then
    mkdir -p $LR_LOG_DIR
    chown $LR_USER:$LR_GRP $LR_LOG_DIR
fi

lr_start () {
    if [ -e $LR_PID ]
    then
        echo "LR Node is already running"
        exit 1
    fi
    echo "Starting LR Node. Log: $LR_LOG   PID: $LR_PID"
    su $LR_USER -c "cd $LR_HOME;source $LR_VIRTUALENV/bin/activate; cd $LR_HOME; uwsgi --enable-threads --no-orphans --ini-paste $LR_HOME/development.ini -H $LR_VIRTUALENV --pidfile $LR_PID --daemonize $LR_LOG; deactivate"
}

lr_stop () {
    if [ -e $LR_PID ]
    then
        echo "Stopping LR Node. Log: $LR_LOG   PID: $LR_PID"
        su $LR_USER -c "source $LR_VIRTUALENV/bin/activate;uwsgi --stop $LR_PID; deactivate"
        su $LR_USER -c "rm -f $LR_PID"
    else
        echo "LR Node not running."
    fi
}

lr_restart () {
    if [ -e $LR_PID ]
    then
        echo "Restarting LR Node. Log: $LR_LOG   PID: $LR_PID"
        su $LR_USER -c "source $LR_VIRTUALENV/bin/activate;uwsgi --stop $LR_PID; deactivate"
        su $LR_USER -c "rm -f $LR_PID"
        su $LR_USER -c "cd $LR_HOME; source $LR_VIRTUALENV/bin/activate; uwsgi --enable-threads --no-orphans --ini-paste $LR_HOME/development.ini -H $LR_VIRTUALENV --pidfile $LR_PID --daemonize $LR_LOG; deactivate"
    else
        echo "LR Node not running.  Please use [start]"
    fi

}


# Carry out specific functions when asked to by the system
case "$1" in
    start)
        echo "Starting script learningregistry "
        lr_start
        ;;
    stop)
        echo "Stopping script learningregistry"
        lr_stop
        ;;
    restart)
        echo "Restarting script learningregistry"
        lr_restart
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac

exit 0
