source 'https://rubygems.org'

gem 'rails', '4.2.5.2'

gem 'spring', group: :development

gem 'sass-rails', '~> 5.0'

# Authentication
gem 'rack-cors', '~> 0.4'
gem 'omniauth', '~> 1.3'
gem 'omniauth-google-oauth2'
gem 'omniauth-amazon', '~> 1.0'
gem 'omniauth-windowslive', github: 'timrogers/omniauth-windowslive', branch: 'patch-1'

# CouchDB
gem 'couchrest_model', '~> 2.0'

# Mailing
gem 'mail_form', '~> 1.5'
gem 'letter_opener', '~> 1.4'

# Token signing and verification
gem 'jwt', '~> 1.5'

# Views
gem 'slim-rails', '~> 3.0'
gem 'simple_form', '~> 3.2'
